<?php
namespace classes;

use classes\Data;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-26 at 00:12:50.
 */
class DataTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Data
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers classes\Data::getDataFormatBanco
     */
    public function testGetDataFormatBanco() {
        $data = new Data('21/05/2014');
        assert($data->getDataFormatBanco() === '2014-05-21');
    }

    /**
     * @covers classes\Data::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
